version: "3.5"

services:
  web:
    build: ./web
    image: xram_memory/web
    container_name: "xram_memory_web"
    env_file:
      - .env
    tmpfs:
      - /tmp
    restart: always
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN}"

  webadmin:
    build: ./webadmin
    image: xram_memory/webadmin
    container_name: "xram_memory_webadmin"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://xram_user:xram_password@xram_memory_db:3306/xram_memory
    tmpfs:
      - /tmp
    restart: always
    volumes:
      - media/:/app/media/
      - static/:/app/staticfiles/
    networks:
      - web
      - internal
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/admin/,/api/v1/,/filer/,/tags_input/"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.docker.network=web"
    ports:
      - 8000

  database:
    image: library/mariadb
    container_name: "xram_memory_db"
    tmpfs:
      - /tmp
    restart: always
    environment:
      - MYSQL_DATABASE=xram_memory
      - MYSQL_USER=xram_user
      - MYSQL_PASSWORD=xram_password
      - MYSQL_ROOT_PASSWORD=root_pswwd
    volumes:
      - database/:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false
    ports:
      - 3306

  files:
    image: kyma/docker-nginx
    container_name: "xram_memory_files"
    env_file:
      - .env
    tmpfs:
      - /tmp
    restart: always
    volumes:
      - media/:/var/www/media/
      - static/:/var/www/static/
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefix:/static/,/media/"

  celery-worker-1:
    build: ./celery_worker
    image: xram_memory/celery_worker
    container_name: "xram_memory_celery_worker_1"
    tmpfs:
      - /tmp
    restart: always
    dns:
      - 8.8.8.8
      - 4.4.4.4
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://xram_user:xram_password@xram_memory_db:3306/xram_memory
    volumes:
      - media/:/app/media/
    networks:
      - internal
    labels:
      - traefik.enable=false

  redis:
    image: wodby/redis:4.0
    container_name: xram_memory_redis
    restart: always
    networks:
      - internal
    sysctls:
      net.core.somaxconn: '511'
    ports:
      - 6379
    labels:
      - traefik.enable=false

  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - web

networks:
  web:
    external: true
  internal:
    internal: true

volumes:
  media:
    external:
      name: xram_memory_webadmin_media

  static:
    external:
      name: xram_memory_webadmin_static

  database:
    external:
      name: xram_memory_db_data

